- hosts: localhost
  gather_facts: no
  tasks:
    - name: Check bootstraped
      stat:
        path: '.bootstraped'
      register: chk_bootstrap

- name: Setup MariaDB as standalone mode
  hosts: commondb
  gather_facts: no
  become: true
  tasks:
    - name: Create temp repos
      copy:
        src: rpm
        dest: /root

    - name: Create repofile
      copy:
        dest: /etc/yum.repos.d/commondb.repo
        content: |
          [commondb]
          name=commondb
          baseurl=file:///root/rpm
          enabled=1
          gpgcheck=0

    - name: Check old mariadb exist
      yum:
        list: installed
      register: yum_installed

    - name: Remove old mariadb (1/2)
      yum:
        name: "{{ item.name }}"
        state: absent
      when: item.version != '10.3.9'
      with_items: "{{ yum_installed.results | selectattr('name','match', 'MariaDB') | list }}"

    - name: Remove old mariadb (2/2)
      yum:
        name: "{{ item.name }}"
        state: absent
      when: item.version != '10.3.9'
      with_items: "{{ yum_installed.results | selectattr('name','match', 'mariadb') | list }}"

    - name: Install MaraiDB
      yum:
        name: MariaDB
        enablerepo: commondb

    - name: Add mariadb openfile limit
      blockinfile:
        create: yes
        path: /etc/systemd/system/mariadb.service.d/override.conf
        block: |
          [Service]
          LimitNOFILE=65535

    - name: Config MariaDB
      template:
        src: templates/my.j2.cnf
        dest: /etc/my.cnf
        owner: mysql
        group: mysql
      register: config_db
      when: hostvars['localhost'].chk_bootstrap.stat.exists == false

    - name: Create mariadb log path
      file:
        state: directory
        path: /var/log/mariadb
        owner: mysql
        group: mysql

    - name: Start mariadb
      systemd:
        name: mariadb
        state: restarted
      when: config_db.changed
      notify:
        - Wait MariaDB

  handlers:
    - import_tasks: handlers.yaml

- name: Init config standalone MariaDB
  hosts: commondb
  gather_facts: no
  become: true
  handlers:
    - import_tasks: handlers.yaml
  tasks:
    - name: Clean MariaDB root unsecure permission
      shell: |
        mysqladmin -u root password "{{ mariadb_root_password  }}"
        mysql -u root -p"{{ mariadb_root_password  }}" -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
        mysql -u root -p"{{ mariadb_root_password  }}" -e "DELETE FROM mysql.user WHERE User=''"
        mysql -u root -p"{{ mariadb_root_password  }}" -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'"
        mysql -u root -p"{{ mariadb_root_password  }}" -e "FLUSH PRIVILEGES"
      notify:
        - Test DB

    - name: Add .my.cnf for local root login
      copy:
        dest: /root/.my.cnf
        content: |
          [client]
          user=root
          password={{ mariadb_root_password }}
          [mysql]
          user=root
          password={{ mariadb_root_password }}

    - name: Add root grant for other nodes can access.
      shell: |
        {% for host in groups['commondb'] %}
        mysql -e "GRANT ALL ON *.* TO 'root'@'{{ hostvars[host]['mysql_address']}}' IDENTIFIED BY '{{ mariadb_root_password }}';"
        {% endfor %}
        mysql -e "FLUSH PRIVILEGES;"

- name: Config first node as Master MariaDB
  hosts: "{{ groups['commondb'][0] }}"
  gather_facts: no
  become: true
  tasks:
    - block:
        - name : Stop first mariaDB for new cluster
          systemd:
            name: mariadb
            state: stopped
          when:
            - groups['commondb'] | length > 1

        - name: Config first MariaDB
          vars:
            set_cluster: true
            action: "bootstrap"
          template:
            src: templates/my.j2.cnf
            dest: /etc/my.cnf
          notify:
            - Wsrep new cluster
          when:
            - groups['commondb'] | length > 1

        - name: Create bootstraped file
          file:
            path: "{{ playbook_dir }}/.bootstraped"
            state: touch
          delegate_to: localhost
          become: false
      when: hostvars['localhost']['chk_bootstrap']['stat']['exists'] == False

  handlers:
    - name: Wsrep new cluster
      shell: |
        /etc/init.d/mysql start --wsrep-new-cluster
        sleep 10
        service mysql start bootstrap
      notify: Record cluster already bootstrap

    - name: Record cluster already bootstrap
      copy:
        content: "true"
        dest: .bootstraped
      delegate_to: localhost

- name: Config other MariaDB nodes
  hosts: "{{ groups['commondb'][1:] }}"
  gather_facts: no
  become: true
  handlers:
    - import_tasks: handlers.yaml
  tasks:
    - name: Config other MariaDB
      vars:
        action: slave
        set_cluster: true
      template:
        src: templates/my.j2.cnf
        dest: /etc/my.cnf
        owner: mysql
        group: mysql
      notify:
        - Restart MariaDB
      when: groups['commondb'] | length > 1

- name: Reconfig first MariaDB exit bootstrap mode
  hosts: "{{ groups['commondb'][0] }}"
  gather_facts: no
  become: true
  handlers:
    - import_tasks: handlers.yaml
  tasks:
    - name: Copy mysql config
      vars:
        set_cluster: true
        action: rejoin
      template:
        src: templates/my.j2.cnf
        dest: /etc/my.cnf
        owner: mysql
        group: mysql
      notify:
        - Restart MariaDB
      when: groups['commondb'] | length > 1

- name: Setup haproxy and keepalived
  hosts: commondb
  gather_facts: no
  become: true
  handlers:
    - import_tasks: handlers.yaml
  tasks:
    - block:
        - name: Install HA componment
          yum:
            name: [keepalived, haproxy, socat]
            enablerepo: commondb

        - name: Setting sysctl values
          sysctl: name={{ item.name }} value={{ item.value }} sysctl_set=yes
          become: true
          with_items:
            - { name: "net.ipv4.ip_nonlocal_bind", value: 1}
            - { name: "net.unix.max_dgram_qlen", value: 128}

        - name: Copy check script
          copy:
            src: templates/chk_haproxy.sh
            dest: /etc/keepalived/chk_haproxy.sh
            mode: 755

        - name: Config keepalived
          template:
            src: templates/keepalived.j2.conf
            dest: /etc/keepalived/keepalived.conf
          notify: Restart keepalived

        - name: Config Haproxy
          template:
            src: templates/haproxy.j2.cfg
            dest: /etc/haproxy/haproxy.cfg
          notify: Restart haproxy
      when: groups['commondb'] | length > 1

- name: Add user for access
  hosts: commondb[0]
  gather_facts: no
  tasks:
    - name: Create user commondb
      shell: |
        mysql -e "CREATE USER 'commondb'@'%' IDENTIFIED BY '{{ commondb_user_password }}';"
        mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'commondb'@'%';"
        mysql -e "grant create user on *.* to commondb with grant option;"
        mysql -e "FLUSH PRIVILEGES;"
